### ISSUE TITLE
不要なコードを削除してください

### ISSUE THREAD

**Issue by matsumoto777** [Waqas-Hirose/CustomViewPractice#8]
AutoLayoutを使用しているため
AutoResizingに関することは不要の認識です。

以前指摘した「func setFramRectは不要」の件、
LabelSwitchViewにも残っています。

開発担当者は不要なコードを常に削除する責任があると思っています。
そうでなければ不要なコードだらけになってソースコードのメンテナンス性は激減します。

不要なコードを他の人間がいちいち調べて指摘しなければいけない状況は、非常に非効率的です。

**Comment by MaroSasaki** [comment]
Because we are using AutoLayout,
my understanding is that AutoResizing related are not necessary.

It has been previously pointed out that "func setFramRect is not necessary".
However, it is still apparent in LabelSwitchView.

The SD is responsible to delete unnecessary codes at all times.
If this is not done, there will be so many unnecessary source codes and that will lower our maintainability (ability to maintenance it efficiently).

If other people need to check for unnecessary codes, it is very inefficient.

**Comment by Waqas-Hirose** [comment]
Required changes have be done.

**Comment by matsumoto777** [comment]
LabelSwitchViewのこれらは必要ですか？

```
    func initCommon() {
        contentMode = .redraw
    }
```

```
        frame = switchView!.frame
```

こちらから指摘したものだけでなく、
ソースコードを全て一度見直して欲しいです。

**Comment by Waqas-Hirose** [comment]
Unnecessary code is removed

**Comment by rujiie** [comment]
```
    func initCommon() {
        contentMode = .redraw
    }
```
がまだ存在します。これは必要ですか?
また、LabelSwitchViewのparentViewは使用されていません。
subViewsHeightもコメントアウトされていますが使用しないのであれば削除してください。
指摘された箇所だけでなく不要なコードは全て削除してください。

LabelSwitchViewのsizeThatFitsに
`super.sizeThatFits(size)`
を追加していますがこれは必要ですか?

**Comment by Waqas-Hirose** [comment]
I have removed unnecessary and commented code and removed
"lbl.sizeThatFits()" and "switchView.sizeThatFits()"

Thanks,
Waqas

**Comment by rujiie** [comment]
1. `contentMode = .redraw` は必要ですか。
2. self.lbl.sizeThatFits(size)とself.switchView.sizeThatFits(size)を削除していますが、私が指摘したのは`super.sizeThatFits(size)`についてです。
    self.lbl.sizeThatFits(size)とself.switchView.sizeThatFits(size)は必要だと思います。

**Comment by Waqas-Hirose** [comment]
"contentMode = .redraw" has been removed and its working fine 

If I delete "**let labelSize = self.lbl.sizeThatFits(size)   let switchSize = self.switchView.sizeThatFits(size)**" then even its' working fine. Please ponder and let me know. Should I delete these two lines or keep them. What can be the difference for removing or having them?

**Comment by Waqas-Hirose** [comment]
Done
